version: '3'
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: docker-tailscale-gost
    # 把 /var/lib/tailscale 映射到当前目录下的 tailscale 文件夹,
    # 以便重启容器后仍能读取并保留已有的机器登录状态.
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    # 启动 tailscaled 时，指定持久化的 state 文件.
    command: tailscaled --state=/var/lib/tailscale/tailscaled.state
    environment:
      - TS_AUTH_KEY=${TAILSCALE_AUTH_KEY}
    # 让容器拥有管理网络的权限.
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    privileged: true
    restart: unless-stopped

  gost:
    image: ginuerzh/gost:latest
    network_mode: "host"
    depends_on:
      - tailscale
    command: -L=socks5://${PROXY_USER}:${PROXY_PASS}@0.0.0.0:1080
    restart: unless-stopped
